spring.application.name=metrics-collector

server.port=8084

spring.datasource.url=jdbc:postgresql://postgres:5432/resilisys
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*

spring.jpa.open-in-view=false