spring.application.name=api-gateway

server.port=8080

management.endpoints.web.exposure.include=*

##################################################
# SERVICE MONITOR
##################################################

spring.cloud.gateway.server.webflux.routes[0].id=service-monitor
spring.cloud.gateway.server.webflux.routes[0].uri=http://service-monitor:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/monitor/**

##################################################
# FAILURE INJECTOR
##################################################

spring.cloud.gateway.server.webflux.routes[1].id=failure-injector
spring.cloud.gateway.server.webflux.routes[1].uri=http://failure-injector:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/inject/**,/metrics

##################################################
# RECOVERY ENGINE
##################################################

spring.cloud.gateway.server.webflux.routes[2].id=recovery-engine
spring.cloud.gateway.server.webflux.routes[2].uri=http://recovery-engine:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/recover/**

##################################################
# METRICS COLLECTOR
##################################################

spring.cloud.gateway.server.webflux.routes[3].id=metrics-collector
spring.cloud.gateway.server.webflux.routes[3].uri=http://metrics-collector:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/metrics/**

##################################################
# CORS
##################################################

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true